version: '3.8'

services:

  db:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  screenshot_bot:
    build: .
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./data/screenshots:/app/data/screenshots
      - ./logs:/app/logs
